### Interactions

# Hug Interaction
interaction.hug:
  - { type: "casual", url: "https://c.tenor.com/PlenvFTbCcAAAAAC/tenor.gif" }
  - { type: "casual", url: "https://c.tenor.com/xIuXbMtA38sAAAAd/tenor.gif" }
  - { type: "casual", url: "https://c.tenor.com/V8f3qPS23LgAAAAC/tenor.gif" }
  - { type: "casual", url: "https://c.tenor.com/JzxgF3aebL0AAAAC/tenor.gif" }
  - { type: "casual", url: "https://c.tenor.com/nHkiUCkS04gAAAAC/tenor.gif" }
  - { type: "casual", url: "https://c.tenor.com/mB_y2KUsyuoAAAAC/tenor.gif" }
  - { type: "casual", url: "https://c.tenor.com/sJATVEhZ_VMAAAAC/tenor.gif" }
  - { type: "casual", url: "https://c.tenor.com/UnpQCW40JekAAAAC/tenor.gif" }
  - { type: "casual", url: "https://c.tenor.com/sl3rfZ7mQBsAAAAC/tenor.gif" }
  - { type: "casual", url: "https://c.tenor.com/4OHcWvReiCgAAAAd/tenor.gif" }
  - { type: "casual", url: "https://c.tenor.com/cBcV5uqNYvYAAAAC/tenor.gif" }
  - { type: "casual", url: "https://c.tenor.com/pcULC09CfkgAAAAC/tenor.gif" }
  - { type: "casual", url: "https://c.tenor.com/xgVPw2QK5n8AAAAC/tenor.gif" }
  - { type: "casual", url: "https://c.tenor.com/z2QaiBZCLCQAAAAC/tenor.gif" }
  - { type: "casual", url: "https://c.tenor.com/nmzZIEFv8nkAAAAC/tenor.gif" }
  - { type: "casual", url: "https://c.tenor.com/vkiqyZJWJ4wAAAAC/tenor.gif" }
  - { type: "romantic", url: "https://c.tenor.com/J7eGDvGeP9IAAAAC/tenor.gif" }
  - { type: "romantic", url: "https://c.tenor.com/YF-rFMgHgDEAAAAC/tenor.gif" }
  - { type: "romantic", url: "https://c.tenor.com/7oCaSR-q1kkAAAAC/tenor.gif" }
  - { type: "romantic", url: "https://c.tenor.com/wWFm70VeC7YAAAAC/tenor.gif" }
  - { type: "romantic", url: "https://c.tenor.com/W9Z5NRFZq_UAAAAC/tenor.gif" }
  - { type: "romantic", url: "https://c.tenor.com/F1VUry86n7kAAAAC/tenor.gif" }
  - { type: "romantic", url: "https://c.tenor.com/M84QPR5DxaUAAAAC/tenor.gif" }
  - { type: "romantic", url: "https://c.tenor.com/stLEkL3l0NAAAAAC/tenor.gif" }
  - { type: "romantic", url: "https://c.tenor.com/dIvoDyyk5LIAAAAC/tenor.gif" }
  - { type: "romantic", url: "https://c.tenor.com/2bWwi8DhDsAAAAAC/tenor.gif" }
  - { type: "romantic", url: "https://c.tenor.com/KD__SewDxK0AAAAC/tenor.gif" }
  - { type: "romantic", url: "https://c.tenor.com/mmQyXP3JvKwAAAAC/tenor.gif" }
  - { type: "comfort", url: "https://c.tenor.com/0vl21YIsGvgAAAAC/tenor.gif" }
  - { type: "comfort", url: "https://c.tenor.com/7f9CqFtd4SsAAAAC/tenor.gif" }
  - { type: "comfort", url: "https://c.tenor.com/nwxXREHNog0AAAAC/tenor.gif" }
  - { type: "comfort", url: "https://c.tenor.com/i2Mwr7Xk__YAAAAC/tenor.gif" }
  - { type: "comfort", url: "https://c.tenor.com/2HxamDEy7XAAAAAC/tenor.gif" }
  - { type: "comfort", url: "https://c.tenor.com/IpGw3LOZi2wAAAAC/tenor.gif" }
  - { type: "comfort", url: "https://c.tenor.com/HYkaTQBybO4AAAAC/tenor.gif" }
  - { type: "comfort", url: "https://c.tenor.com/4KCRNlvol8AAAAAC/tenor.gif" }
  - { type: "comfort", url: "https://c.tenor.com/8o4fWGwBY1EAAAAC/tenor.gif" }
  - { type: "comfort", url: "https://c.tenor.com/c8M8yU1q6c4AAAAC/tenor.gif" }
  - { type: "comfort", url: "https://c.tenor.com/Ct4bdr2ZGeAAAAAC/tenor.gif" }
  - { type: "comfort", url: "https://c.tenor.com/Pd2sMiVr09YAAAAC/tenor.gif" }
  - { type: "comfort", url: "https://c.tenor.com/SPs0Rpt7HAcAAAAC/tenor.gif" }
  - { type: "comfort", url: "https://c.tenor.com/EnfEuWDXthkAAAAC/tenor.gif" }
  - { type: "comfort", url: "https://c.tenor.com/fLxZt7jo1YEAAAAC/tenor.gif" }